find_path(SIMGRID_INCLUDE_DIR simgrid/s4u.hpp)
find_library(SIMGRID_LIBRARY NAMES simgrid)

if(SIMGRID_INCLUDE_DIR AND SIMGRID_LIBRARY)
  set(SIMGRID_FOUND TRUE)
  set(SimGrid_INCLUDE_DIRS ${SIMGRID_INCLUDE_DIR})
  set(SimGrid_LIBRARIES ${SIMGRID_LIBRARY})
else()
  set(SIMGRID_FOUND FALSE)
endif()

mark_as_advanced(SIMGRID_INCLUDE_DIR SIMGRID_LIBRARY)